version: 0.2
phases:
  install:
    runtime-version:
      docker: 19
    pre_build:
      commands:
        - echo Build Backend docker images for testing...
        - docker build -t spbryan/deploy-test .
    build:
      commands:
        - echo Build started on `date`
        # Run test with build docker images
        - echo Run tests...
        - docker run spbryan/deploy-test npm test
    post_build:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push spbryan/deploy-test